server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_SERVER_URL}
    username: ${DB_USERNAME}
    password: ${DB_USERNAME}
  flyway:
    enabled: true
    url: ${DB_SERVER_URL}
    user: ${DB_USERNAME}
    password: ${DB_USERNAME}
  jpa:
    properties:
      hibernate:
        default_schema: {DB_SCHEMA}
        jdbc:
          time_zone: UTC
    show-sql: false

logging:
  pattern:
    dateFormat: yyyy-MM-dd HH:mm:ss.SSS ZZZ
  level:
    co.zip.candidate.userapi: info
